### ISSUE TITLE
Failed at 'Add Subscriptions'…

### ISSUE THREAD

**Issue by kklod** [j54j6/YoutubeDL-Downloader#1]
![image](https://github.com/j54j6/YoutubeDL-Dowloader/assets/50442661/68c5abcc-987a-44bb-b831-801f55a8858e)

**Comment by j54j6** [comment]
Hey, 

it seems like I made some errors and forgot to push the changes :) - Downlaod the new Version and try again

**Comment by kklod** [comment]
> Hey,
> 
> it seems like I made some errors and forgot to push the changes :) - Downlaod the new Version and try again

still the same…

I've asked chatgpt, it said that it was the problem with my python(version=3.9.2)~
maybe it's true, but I can't upgrade python on my raspberrypi…sigh！

**Comment by j54j6** [comment]
Please download the file "yt_manager.py" and replace it manually. 

Whioch python version do use use? - I will check myself

**Comment by kklod** [comment]
> Please download the file "yt_manager.py" and replace it manually.
> 
> Whioch python version do use use? - I will check myself

I removed all the old files and git clone new packages just now , the problem still exists!
About the version of python, as I mentioned, it's 3.9.2…

**Comment by j54j6** [comment]
Hey, 

sorry for the delay. I have now tested your version and turns out, some of the features I use are only supported in Pyhton 3.10+. 
I tried to add support for python 3.9 but there are multiple things I need to change to support python 3.9. Since it is near it's EOL the work does not outweight the use. So I reverted the changes I already made.

But if you have a raspberry Pi, you can install Python 3.11 with the base image. Python 3.11 is supported. I have tried my old Raspi 2b. You can add another repo and install it from there :)

**Comment by kklod** [comment]
> Hey,
> 
> sorry for the delay. I have now tested your version and turns out, some of the features I use are only supported in Pyhton 3.10+. I tried to add support for python 3.9 but there are multiple things I need to change to support python 3.9. Since it is near it's EOL the work does not outweight the use. So I reverted the changes I already made.
> 
> But if you have a raspberry Pi, you can install Python 3.11 with the base image. Python 3.11 is supported. I have tried my old Raspi 2b. You can add another repo and install it from there :)

Thanks！ I'll try it later.
