### ISSUE TITLE
video quality

### ISSUE THREAD

**Issue by slavikfoxy** [j54j6/YoutubeDL-Downloader#4]
Can I change the video quality when downloading from ph? I want to download 240p, 360p instead of 1080p

**Comment by j54j6** [comment]
Hey, 

currently there is no "out-of-the-box function" to confugure this. The main intend was to downlaod the best possible format :) - 
I will create a config entry for this ASAP. Since I am very busy at the time this need some time :/ 

But you can modify the code (1 line) to get what you want as a workaround:
-> To change the quality of the downloaded videos you need to tell youtube-dl that you want a specific format.
you can do this by editing the "project_functions.py" and modify the function that returns the youtube-dl config array (line 2251).
If you change the line: " 'format': 'best' " to " 'format': mp4[height=240] " it should work :) -> If you want 360p you need to change the 240 to 360 ;)

I will leave the issue open until I added the cli / config option for this :)

**Comment by j54j6** [comment]
Hey, 

I created a new release today (v1.1) - it gives you the ability to define the output format per subscription, per video or globally.

Please check it out and test it ^^
